### ISSUE TITLE
How to adapt to streaming from pub/sub?

### ISSUE THREAD

**Issue by evanhenry** [silviulica/WorkflowExamples#1]
hello, 

would it be possible to adapt this notebook to launch a pipeline that uses data from a pub/sub subscription and saves it into a big query table?

possibly using `apache_beam.io.gcp.pubsub.PubSubSource`?  https://beam.apache.org/documentation/sdks/pydoc/2.0.0/apache_beam.io.gcp.html?highlight=pubsub#module-apache_beam.io.gcp.pubsub 

I am having trouble understanding how this would look like.

Cheers,
Evan

**Comment by silviulica** [comment]
Hi,
Please ping directly the Apache Beam project people to guide you. I am sure they have forums on beam.apahe.org. Sorry but I moved to other pastures and I do not have context anymore to update the notebook.
Thanks!
